// Code generated by "stringer -type=OperationType"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpUnused-0]
}

const _OperationType_name = "OpUnused"

var _OperationType_index = [...]uint8{0, 8}

func (i OperationType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OperationType_index)-1 {
		return "OperationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperationType_name[_OperationType_index[idx]:_OperationType_index[idx+1]]
}
