// Code generated by "stringer -type=ProtocolType"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProtocolTypeEvent-0]
	_ = x[ProtocolTypeRequest-1]
	_ = x[ProtocolTypeResponse-2]
}

const _ProtocolType_name = "ProtocolTypeEventProtocolTypeRequestProtocolTypeResponse"

var _ProtocolType_index = [...]uint8{0, 17, 36, 56}

func (i ProtocolType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ProtocolType_index)-1 {
		return "ProtocolType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProtocolType_name[_ProtocolType_index[idx]:_ProtocolType_index[idx+1]]
}
