// Code generated by "stringer -type=EquipmentSlot"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EquipmentSlot_MainHand-0]
	_ = x[EquipmentSlot_OffHand-1]
	_ = x[EquipmentSlot_Head-2]
	_ = x[EquipmentSlot_Chest-3]
	_ = x[EquipmentSlot_Shoes-4]
	_ = x[EquipmentSlot_Bag-5]
	_ = x[EquipmentSlot_Cape-6]
	_ = x[EquipmentSlot_Mount-7]
	_ = x[EquipmentSlot_Potion-8]
	_ = x[EquipmentSlot_Food-9]
}

const _EquipmentSlot_name = "EquipmentSlot_MainHandEquipmentSlot_OffHandEquipmentSlot_HeadEquipmentSlot_ChestEquipmentSlot_ShoesEquipmentSlot_BagEquipmentSlot_CapeEquipmentSlot_MountEquipmentSlot_PotionEquipmentSlot_Food"

var _EquipmentSlot_index = [...]uint8{0, 22, 43, 61, 80, 99, 116, 134, 153, 173, 191}

func (i EquipmentSlot) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EquipmentSlot_index)-1 {
		return "EquipmentSlot(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EquipmentSlot_name[_EquipmentSlot_index[idx]:_EquipmentSlot_index[idx+1]]
}
